# # version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - ELASTIC_PASSWORD=changeme
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - xpack.security.transport.ssl.enabled=true

    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q 'green'"]
      interval: 30s
      timeout: 10s
      retries: 3

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.1
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    depends_on:
      elasticsearch:
        condition: service_healthy

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.10.1
    container_name: filebeat
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - E:/Project_4/logs:/var/log
    depends_on:
      logstash:
        condition: service_healthy

volumes:
  es_data:
    driver: local

# services:
#   elasticsearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
#     container_name: elasticsearch
#     environment:
#       - discovery.type=single-node
#       - ES_JAVA_OPTS=-Xms512m -Xmx512m
#       - xpack.security.enabled=false
#     volumes:
#       - es_data:/usr/share/elasticsearch/data
#     ports:
#       - "9200:9200"
#       - "9300:9300"
#     healthcheck:
#       test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q 'green'"]
#       interval: 30s
#       timeout: 10s
#       retries: 3

#   logstash:
#     image: docker.elastic.co/logstash/logstash:8.10.0
#     container_name: logstash
#     volumes:
#       - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
#     depends_on:
#       elasticsearch:
#         condition: service_healthy
#     ports:
#       - "5044:5044"

#   kibana:
#     image: docker.elastic.co/kibana/kibana:8.10.0
#     container_name: kibana
#     environment:
#       - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#     depends_on:
#       elasticsearch:
#         condition: service_healthy
#     ports:
#       - "5601:5601"

#   filebeat:
#     image: docker.elastic.co/beats/filebeat:8.10.0
#     container_name: filebeat
#     volumes:
#       - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
#     depends_on:
#       elasticsearch:
#         condition: service_healthy

# volumes:
#   es_data:
#     driver: local
